### ISSUE TITLE
Gas Prices data set review

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/ons-faster-economic-indicators#27]
Review the dataset, providing suggestion for changes.

1. Look at the csv
2. Look at the json file
3. Look at the associated concept schemes if they are separate
4. Validate the serialised output folder
5. Provide the feedback as a comment on github

**Comment by sazzadur-ons** [comment]
Build failed last time. 
But Build successful this time.
Build Complete @ /Users/sazzadurrahman/projects/ons-fei/ons-fei/gas_prices/out

**Comment by BenHowland** [comment]
Feedback:

CSV

•	Do we need to include SAP (System Average Price) anywhere in the csv.
•	Will we need to keep the four decimals.

JSON file

•	There is no dataset_issued timeframe.
•	Creator needs to be added.
•	We could include from_existing to give more detail to the metadata.

**Comment by abdulkasim1** [comment]
# Gas Prices data set review

## Dataset metadata

- [  ] Creator not provided
- [  ] Date when dataset was issued
- [  ] Time period covered by dataset should be provided in summary (e.g. "Number of flights to, from, and within the UK between 1 January 1970 and 19 January 2038")
